# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0006_merge_20170612_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleDevice',
        ),
    ]
